### ISSUE TITLE
Fails to build in poudriere: rm -f -r /tmp/npm-cache -- Permission denied

### ISSUE THREAD

**Issue by Zirias** [tagattie/FreeBSD-Electron#1]
Hi,

I can't build this port in poudriere. I uploaded the build log here:
https://pastebin.com/nKWfvj5W
A lot of npm output is stripped out (`[...]`) to fit the maximum paste size.

Interesting thing is: the poudriere build executes the `post-fetch` target 3 times, and mysteriously fails on the third run trying to remove `/tmp/npm-cache`.

Could it make sense to use a different target (maybe `pre-extract`) for `npm install`, so poudriere doesn't repeat it all over? Could it make sense to use a tmp directory inside `${WRKDIR}`?

**Comment by tagattie** [comment]
Hi, thanks for your interest in this port.

> Interesting thing is: the poudriere build executes the `post-fetch` target 3 times, and mysteriously fails on the third run trying to remove `/tmp/npm-cache`.

The `post-fetch` target are executed 3 times in my poudriere environment and I don't know why. But removing `/tmp/npm-cache` does not fail.

The failure may be due to `BUILD_AS_NON_ROOT` (in poudriere.conf) is set to `yes` (by default).

In my env, this variable is set to `no` because `CCACHE_DIR` is set and `CCACHE_DIR_NON_ROOT_SAFE` is not set.

Can you try with `BUILD_AS_NON_ROOT=no` and see if the error goes away?

> Could it make sense to use a different target (maybe `pre-extract`) for `npm install`, so poudriere doesn't repeat it all over? Could it make sense to use a tmp directory inside `${WRKDIR}`?

I suspect poudriere does not allow network access other than the `fetch` phase by default. But if `npm` can access network during `pre-extract` target, the change does make sense.

**Comment by Zirias** [comment]
Hi, thanks for the quick reply! This of course makes sense, especially if the fetch phase is indeed done as root, so a non-root user can't remove these files later.

I'll test that as soon as I have the time (maybe later, probably tomorrow). If that's indeed the problem, I'll get a fork of your repository to try and come up with a stable solution ...

Thanks for your work so far :)

**Comment by Zirias** [comment]
I can now confirm your assumption about `BUILD_AS_NON_ROOT` is correct -- I took a fork trying to come up with a decent solution (using the 5-0-x branch now).

First thing, I think you shouldn't use `${TMPDIR}`, according to https://www.freebsd.org/doc/en/books/porters-handbook/porting-wrkdir.html
So I'll try to fetch to `${WRKDIR}` instead. The `BUILD_AS_NON_ROOT` problem could be solved with a `chmod a+w ...` I guess.

I still had no luck preventing to run `npm install` multiple times. It seems `post-fetch` is a `PHONY` target and somehow I can't get `make` to depend on a normal target and treat it as such ...

Maybe the cleanest solution would be to have `post-fetch` build a tarball in `${DISTFILES}` containing the `npm_modules` and not do anything if this tarball is already there. But I'm not sure one can rely on `tar` creating the exact same archive (so the SHA256 sums match) on all machines? So maybe this is a bad idea.

**Comment by tagattie** [comment]
> First thing, I think you shouldn't use `${TMPDIR}`, according to https://www.freebsd.org/doc/en/books/porters-handbook/porting-wrkdir.html

Thanks for pointing the URL. I agree with `${TMPDIR}` shouldn't be used. But...

> So I'll try to fetch to `${WRKDIR}` instead. The `BUILD_AS_NON_ROOT` problem could be solved with a `chmod a+w ...` I guess.

Fetching to `${WRKDIR}` doesn't seem a good idea because it is wiped before the `extract` phase. So the fetched node_modules will be gone... :frowning_face:

**Comment by Zirias** [comment]
I tried hard now to get a reproducible tar archive from the node_modules downloaded by `npm install` without success so far :(

This leads me to assume builds won't be reproducible either when using `npm install`? I can do a hacky approach by having the fetch phase do `npm install` and create a tarball from it in `${DISTDIR}`, so extract can pick that up -- **without** listing it in `DISTFILES`, so checksums don't matter. But that's not really a good way to do things. Isn't there a way to get reproducible results from `npm install`? :o

**Comment by Zirias** [comment]
Just in case you want to see what I'm trying:
https://github.com/Zirias/FreeBSD-Electron/commit/33f44b71877d75e3e99e49f39fa9c213c2653f37

still testing right now -- if I succeed creating a reproducible distfile from the `npm install` result, I'll send you a pull request :)

**Comment by lapo-luchini** [comment]
Uh, I assumed that using a `package-lock.json` was just about having a reproducible `node_modules` directory… it doesn't?

**Comment by Zirias** [comment]
Well, I don't know much about npm and in fact don't like that tool ;) I guess this should make sure to have the exact versions though, therefore I'm still optimistic I might find a way to create a reproducible tarball -- I'm experimenting with `mtree` for that, sorting all entries, fixing ownership, the next thing I'll try is giving fixed timestamps to the archived files. But if it's really impossible to reproduce the same tarball, something in the node_modules must be different as well, that's all I meant.

**Comment by tagattie** [comment]
> Isn't there a way to get reproducible results from `npm install`? :o

`npm ci` instead of `npm install` may help. `npm ci` appears to be exatly for this kind of purpose.
https://docs.npmjs.com/cli/ci.htm

I tried the following and confirmed these two `node_modules` directories were exactly same other than some timestamps.

```
mkdir /tmp/TMP1 /tmp/TMP2
cp package.json package-lock.json /tmp/TMP1
cp package.json package-lock.json /tmp/TMP2
cd /tmp/TMP1 && npm ci
cd /tmp/TMP2 && npm ci
diff -ur /tmp/TMP1 /tmp/TMP2
(diff command produces no output)
```

**Comment by Zirias** [comment]
Thanks for this! Just created a pull request for review -- I can now create a reproducible tarball from the npm modules :)

**Comment by Zirias** [comment]
I guess this can be considered solved, at least in your 5-0-x branch (which I expect to become the new master some day?) :) Definitely solved for me, thanks!
