### ISSUE TITLE
devel/electron6: build fails on FreeBSD 13.0-BETA1/amd64

### ISSUE THREAD

**Issue by ehaupt** [tagattie/FreeBSD-Electron#118]
I noticed that devel/electron6 fails to build on FreeBSD 13.0-BETA1/amd64. See the attached, compressed poudriere build log:

[electron6-6.1.12_1.log.gz](https://github.com/tagattie/FreeBSD-Electron/files/5997051/electron6-6.1.12_1.log.gz)

**Comment by tagattie** [comment]
I'm on this.

**Comment by tagattie** [comment]
The port should now build on FreeBSD 13. Can you check when you have time?

**Comment by ehaupt** [comment]
I can confirmed. It builds now perfectly. Thank you.

[electron6-6.1.12_1.log.gz](https://github.com/tagattie/FreeBSD-Electron/files/6008877/electron6-6.1.12_1.log.gz)

**Comment by tagattie** [comment]
Thanks for the confirmation. Closing this.
