### ISSUE TITLE
Makefile post build issue

### ISSUE THREAD

**Issue by tagattie** [tagattie/FreeBSD-Electron#15]
A bug has been reported at Bugzilla:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239459

**Comment by tagattie** [comment]
I guess this is an pkg-plist issue when the option DIST is set OFF.

The current pkg-plist seems to lack `%%DIST%%` prefix where needed.

**Comment by pizzamig** [comment]
I ran a build with DIST disabled using my branch and it works.
Now I'm waiting to build with DIST enabled again to check that the plist is correct in this case as well.
In general, I guess it makes sense to remove DIST for the default options, it doesn't make a lot of sense for users to have those zip blobs in the package.

**Comment by tagattie** [comment]
The zip files are for use with `electron-packager` or `electron-builder` and I thought it was good to include those blobs in the package instead of downloading from the internet.

But only (work in progress) `vscode` port currently depends on electron4 port and it doesn't use those javascript modules, so it would be good to remove DIST from the default options for now.

I will update the port accordingly.

Thanks for the suggestion!

**Comment by tagattie** [comment]
Hi @pizzamig,

I uploaded a patch (fix pkg-plist and change DIST off by default) to the Bugzilla:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239459

Could you take care of this PR as well?

**Comment by pizzamig** [comment]
sure, I'll run my default set of tests and I will commit&close the PR.
One thing as a side note for the next time: the PR has the maintainer-feedback flag set to '?' (automatically set by bugzilla)
When you reply, set it to '+'. It only means that you're taking care of it and no maintainer timeout will be triggered

**Comment by pizzamig** [comment]
Patch committed and PR closed. Closing this issue as well.
