### ISSUE TITLE
Please skip 5.0 and use 6.0 directly.

### ISSUE THREAD

**Issue by zoujiaqing** [tagattie/FreeBSD-Electron#18]
Electron 6.0 is released.

Can use latest version 6.0, thanks.

**Comment by tagattie** [comment]
Well, electron 5 port has been out there for some time although it is not (yet) an official port.
https://github.com/tagattie/FreeBSD-Electron/tree/master/devel/electron5

I will work on electron 6 as well.

**Comment by zoujiaqing** [comment]
Thanks tagattie :)
