### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by lapo-luchini** [tagattie/FreeBSD-Electron#2]
```
install: /usr/local/ports/work/home/lapo/ports/devel/electron/work/electron-4.2.0/src/out/Release/LICENSE: No such file or directory
*** Error code 71
```

I worked it around like this:

```
sudo touch /usr/local/ports/work/home/lapo/ports/devel/electron/work/electron-4.2.0/src/out/Release/LICENSE
sudo touch /usr/local/ports/work/home/lapo/ports/devel/electron/work/electron-4.2.0/src/out/Release/LICENSES.chromium.html
sudo touch /usr/local/ports/work/home/lapo/ports/devel/electron/work/electron-4.2.0/src/out/Release/version
sudo make install
```

I'm running on `FreeBSD 12.0-RELEASE-p3 GENERIC amd64`.

**Comment by tagattie** [comment]
There was a discrepancy between the generated files and the contents of the `pkg-plist` file when DIST option was OFF.

I have changed the `Makefile` to always generate those license and version files.

Thanks for the report.

**Comment by tagattie** [comment]
Closing with commit https://github.com/tagattie/FreeBSD-Electron/commit/4c2f129bc1459eed3ad317ed8200119830c9e38f.
