### ISSUE TITLE
electron4: update to 4.2.12_1

### ISSUE THREAD

**Issue by tagattie** [tagattie/FreeBSD-Electron#34]
Hi @pizzamig,

Happy new year!
I have made some changes to electron4 port. Can you check and commit the changes?

Summary of changes:
- Remove `CONFLICT_INSTALL` (now multiple versions of electron can coexist)
- Install node headers for native modules building
  - This makes it unnecessary to download relevant headers from the net in dependent ports
- Add a test dependency (devel/py-python-dbusmock)
  - This is a new port. A PR submitted at: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243029
  - (I hope you take care of the PR too.)
- Remove `TEST` option.

I will make similar changes to the rest of the electron ports.

**Comment by tagattie** [comment]
>   * This is a new port. A PR submitted at: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243029
>   * (I hope you take care of the PR too.)

The has been committed. Thanks to tcberner@.

**Comment by pizzamig** [comment]
Hi and happy new year!
I'd like to add some changes before to commit it.
Mainly 2:
* I'd like to move ELECTRON_VER definition to an external file, so it can be imported by other ports, avoiding complicated replication

**Comment by tagattie** [comment]
Hi @pizzamig,

Do you see any problems with the changes? Please let me know if any issues.

**Comment by tagattie** [comment]
Hi @pizzamig,

Now the builds of electron4 and electron6 are failing due to update of snappy.

I have added a patch to fix that, which was obtained from:
https://svnweb.freebsd.org/ports?view=revision&revision=523845

I hope you can review the changes and commit them at your earliest convenience.

**Comment by pizzamig** [comment]
Building right now.
Sorry for the too long delay, I'll commit those changes in the day. Then I'll focus on electron6 and vscode

**Comment by tagattie** [comment]
Welcome back :smile:

You may have noticed there is a file named `bsd.electron.mk`. Please do not commit the file. I'm now trying to write `Mk/Uses/node.mk` and `Mk/Uses/electron.mk` which should be used instead according to the suggestion from bapt@.

**Comment by pizzamig** [comment]
committed.
There was already some work on node.mk, but it never landed.
The main reasons is that node modules shouldn't be managed in the portstree or any other packaging system, so there was very few use cases and we ended up in having subports for npm and yarn.
