### ISSUE TITLE
electron4: one more change

### ISSUE THREAD

**Issue by tagattie** [tagattie/FreeBSD-Electron#36]
Hi @pizzamig,

Thanks for committing the changes to `devel/electron4`. I would like to ask you to commit just another change. The summary of change is:
- Add `ELECTRON_VER_MAJOR` to Makefile.version
- Use `ELECTRON_VER_MAJOR` in place of `PKGNAMESUFFIX`

The variable can be used by other dependent ports to know a major version of electron.

Please check attached the diff file and commit it if OK. This makes the git repo and the official tree in complete sync.

[electron4-4.2.12_1.diff.txt](https://github.com/tagattie/FreeBSD-Electron/files/4125987/electron4-4.2.12_1.diff.txt)

**Comment by pizzamig** [comment]
Yes, I'll do ASAP. This kind of changes do not modify the final result, so no PORTREVISION bump is needed and I can commit it after an easy build test

**Comment by tagattie** [comment]
Thanks for committing this as well!
