### ISSUE TITLE
electron6: commit some leftovers

### ISSUE THREAD

**Issue by tagattie** [tagattie/FreeBSD-Electron#37]
Hi @pizzamig,

Thanks for committing the changes to `devel/electron6`. I have found there are some leftovers. Could you commit another change? The changes are:
- Use `ELECTRON_VER_MAJOR` in place of `PKGNAMESUFFIX`
- Remove unused Makefile.test file
- Rename wrongly named snappy patch file

Please check attached the diff file for details.

[electron6-6.1.7.diff.txt](https://github.com/tagattie/FreeBSD-Electron/files/4173841/electron6-6.1.7.diff.txt)

**Comment by pizzamig** [comment]
Thanks for noticing.
I've now written a rsync script to catch the changes. Test the build and then commit

**Comment by tagattie** [comment]
Thank you!!
