### ISSUE TITLE
electron4, electron6, and electron7: build error on -CURRENT

### ISSUE THREAD

**Issue by tagattie** [tagattie/FreeBSD-Electron#39]
The builds on -CURRENT are failing with the following error. This appears to be due to the recent upgrade to LLVM 10.
```
In file included from ../../third_party/angle/src/libANGLE/renderer/vulkan/GlslangWrapper.cpp:18:
In file included from ../../third_party/glslang/src/SPIRV/GlslangToSpv.h:42:
In file included from ../../third_party/glslang/src/SPIRV/SpvTools.h:47:
In file included from ../../third_party/glslang/src/SPIRV/../glslang/MachineIndependent/localintermediate.h:42:
In file included from ../../third_party/glslang/src/glslang/Public/../MachineIndependent/../Include/intermediate.h:55:
In file included from ../../third_party/glslang/src/glslang/Public/../Include/../Include/Common.h:108:
./../third_party/glslang/src/glslang/Public/../Include/PoolAlloc.h:307:54: error: 'operator=' is a private member of 'glslang::TPoolAllocator'
    void setAllocator(TPoolAllocator* a) { allocator = *a; }
                                           ~~~~~~~~~ ^ ~~
./../third_party/glslang/src/glslang/Public/../Include/PoolAlloc.h:244:21: note: declared private here
    TPoolAllocator& operator=(const TPoolAllocator&);  // don't allow assignment operator
                    ^
1 error generated.
```

**Comment by tagattie** [comment]
After googling the error message, I found the following URLs:
- https://github.com/KhronosGroup/glslang/issues/1869
- https://github.com/KhronosGroup/glslang/pull/2010

Just removing the `setAllocator` line seems suffice. I will update the repo accordingly.

**Comment by tagattie** [comment]
electron4 has been fixed with commit https://github.com/tagattie/FreeBSD-Electron/commit/b39f74f264b88ecb7e1128eebaf7eb4f119f8ea7.

**Comment by tagattie** [comment]
electron7 is also affected.

Reported by: pkg-fallout

**Comment by tagattie** [comment]
electron6 has been fixed with commit https://github.com/tagattie/FreeBSD-Electron/commit/d2219ee16c526f63635aaec2c40b818357e2f0ae.

**Comment by tagattie** [comment]
electron7 has been fixed with commit https://github.com/tagattie/FreeBSD-Electron/commit/2ce3c954c6d1f9efc85d28cdd047c62e1d3872b2.

**Comment by tagattie** [comment]
Hi @pizzamig and @ehaupt,

Can either of you check and commit the changes for electron4, electron6, and electron7 to fix build with recent -CURRENT?

In addition to build fixes, I have removed some unnecessary patches from electron6.

**Comment by ehaupt** [comment]
Hi @tagattie , I am looking into it, however, it's going to take a while for all the test builds to finish.

**Comment by ehaupt** [comment]
Hi @tagattie, I've updated the electron4, electron6 and electron7 ports. Thanks again for your swift work and sorry for the delay.

**Comment by tagattie** [comment]
Thank you!!
