### ISSUE TITLE
Add the port to the official FreeBSD repo

### ISSUE THREAD

**Issue by pizzamig** [tagattie/FreeBSD-Electron#4]
Hi. First of all, thanks for moving forward this work.

It would be nice to have this port committed in the official portstree.
I'm currently testing the build on my poudriere instances.
I'm a port committer, so I would take care of all small details and of committing in the repo.
Would you like to be the maintainer of the port?
What about having electron4 and electron5 ports, to support 2 different major releases? Does it make any sense to you?

thanks again for your precious work
pizzamig

**Comment by tagattie** [comment]
Hi, thanks for your interest in this port.

It would be great to see it imported into the official tree. I would be happy to maintain the port.

I'm using VS Code with electron built using the port for a while and feel it usable. However, some functions (crash reporter, memory dump) are missing and there is a problem regarding clipboard function. So some unit tests currently don't pass.

Is it OK to be an official port?

> What about having electron4 and electron5 ports, to support 2 different major releases?

I agree that having 4 and 5 ports is good since both are supported by upstream.

**Comment by pizzamig** [comment]
I'll do some small adjustment to the port, and, please, add your email address in the  MAINTAINER field of the Makefile.
Even if the port is not perfect, but usable, it's fine, probably you'll get some PR in the FreeBSD Bugzilla about it.
Maybe we can release with the suffix -devel, normally used to publish ports not yet fully stable.

**Comment by tagattie** [comment]
I've just updated MAINTAINER's email address.

Please let me know any other things I can do to help this port become official.

I will merge changes regarding electron unit tests to 5-0-x branch. So I hope you'll first take care of electron4 port.

**Comment by pizzamig** [comment]
Thanks!
I've just submitted a PR to add the suffix for electron4.

In order to support electron4 and electron5 at the same time, the project tree should be slightly different: the root folder will contain all files not to be mirrored in the ports tree, like .gitignore and README.md
then a folder called electron4 that contains Makefile & friends to build electron 4.x and a folder called electron5 that contains Makefile & friends to build electron 5.x
After that, we can evaluate some refactoring.

**Comment by tagattie** [comment]
A directory structure like this makes sense?

```
.
├── .gitignore
├── README.md
└── devel
    ├── electron4
    │   └── Makefile
    │       (...)
    └── electron5
        └── Makefile
            (...)
```

**Comment by pizzamig** [comment]
That's awesome, because it mimics the content of the porstree.

**Comment by tagattie** [comment]
I've just pushed the directory structure change to the repo. Can you take a look?

**Comment by pizzamig** [comment]
that's great!

**Comment by pizzamig** [comment]
Hi.
I'd like to finally add electron4 to the tree and commit there.
Do you think is NOW a good moment? Do you want me to wait to be sure that the clipboard is really working?

**Comment by lapo-luchini** [comment]
@tagattie a bit OT here, but as you mentioned using it with VSCode, would you mind writing something about that?
I tried with both Linux and portable VSCode but it fails looking for `.so` files.
(I'd like to use it, write a Wiki page maybe to help people using it and/or/maybe create a Port too)

**Comment by tagattie** [comment]
@pizzamig I'd like to do some quick testing with a patched-electron build. So could you give me some time? It won't be long.

**Comment by tagattie** [comment]
@lapo-luchini An experimental VS Code port is available at the following URL:
https://github.com/tagattie/FreeBSD-VSCode

I'm now trying to make the port poudriere-compatible, so it may be currently broken. If so, please use a package at the Releases page.

**Comment by tagattie** [comment]
@pizzamig I ran the clipboard-related unit test with the patched version and it didn't fail. So I think the clipboard issue has been fixed. If anything I can do more to make it the official tree, please let me know.

**Comment by pizzamig** [comment]
electron4 is now in the ports tree!
https://svnweb.freebsd.org/ports/head/devel/electron4/

I will close this issue, so we can now focus on electron5

**Comment by tagattie** [comment]
Great news! Thanks for taking your time for polishing and committing the port :smile:
