### ISSUE TITLE
patch phase fails

### ISSUE THREAD

**Issue by pizzamig** [tagattie/FreeBSD-Electron#9]
I was trying to work on the CURRENT fail issue, and I end up with this weird issue.
On my laptop, a CURRENT, `make patch` fails:
```
===>  Applying FreeBSD patches for electron4-4.2.3
1 out of 4 hunks failed--saving rejects to base/BUILD.gn.rej
=> FreeBSD patch patch-base_BUILD.gn failed to apply cleanly.
```
The first hunk of `patch-base_BUILD.gn` is the issue. Looking at the original file, the line that has to be substituted is wrong (a `!use_sysroot &&`) is missing.
I'm trying to understand what's happening and I'll try to provide a patch to fix it.

**Comment by tagattie** [comment]
Is the working directory (WRKDIR) subdirectory of a ports git repository?

If so, can you try either of the following to see the error goes away?
- Rename `.git` temporarily to other name (say `.git.bak`)
- Set WRKDIR somewhere outside of the git repository

`git apply` at `pre-patch` phase appears to fail for some reason when WRKDIR is under a git repo.

**Comment by pizzamig** [comment]
thanks, the WRKDIR tip is working. however, I've noticed in the past that some git hooks landed in my .git directory automagically.
It seems that some build steps involving git is messing around.
A separated WRKDIR is the best approach for now.
I've submitted a change in the README to remember of it
